using Microsoft.EntityFrameworkCore;
using QuanLyNhaSach.Models;

namespace QuanLyNhaSach.Helpers
{
    public static class DatabaseSeeder
    {
        public static void Seed(ModelBuilder modelBuilder)
        {
            SeedThamSo(modelBuilder);
            SeedSach(modelBuilder);
            SeedPhieuNhapSach(modelBuilder);
            SeedChiTietPhieuNhap(modelBuilder);
            SeedHoaDonBanSach(modelBuilder);
            SeedChiTietHoaDon(modelBuilder);
            SeedKhachHang(modelBuilder);
            SeedPhieThu(modelBuilder);
        }

        private static void SeedThamSo(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ThamSo>().HasData(
                new ThamSo
                {
                    Id = 1,
                    SoLuongNhapToiThieu = 150,
                    SoLuongTonToiDa = 300,
                    SoLuongTonToiThieu = 20,
                    TienNoToiDa = 20000,
                    QuyDinhTienThuTienNo = true
                }
            );
        }

        private static void SeedPhieThu(ModelBuilder modelBuilder)
        {
            var seedDate = new DateTime(2023, 1, 1);

            modelBuilder.Entity<PhieuThu>().HasData(
                new PhieuThu { MaPhieuThu = 1, MaKhachHang = 1, NgayThu = seedDate.AddDays(92), SoTienThu = 78654 },
                new PhieuThu { MaPhieuThu = 2, MaKhachHang = 1, NgayThu = seedDate.AddDays(120), SoTienThu = 71495 },
                new PhieuThu { MaPhieuThu = 3, MaKhachHang = 1, NgayThu = seedDate.AddDays(130), SoTienThu = 3793 },
                new PhieuThu { MaPhieuThu = 4, MaKhachHang = 1, NgayThu = seedDate.AddDays(137), SoTienThu = 12531 },
                new PhieuThu { MaPhieuThu = 5, MaKhachHang = 2, NgayThu = seedDate.AddDays(91), SoTienThu = 36144 },
                new PhieuThu { MaPhieuThu = 6, MaKhachHang = 2, NgayThu = seedDate.AddDays(92), SoTienThu = 18083 },
                new PhieuThu { MaPhieuThu = 7, MaKhachHang = 2, NgayThu = seedDate.AddDays(96), SoTienThu = 52550 },
                new PhieuThu { MaPhieuThu = 8, MaKhachHang = 3, NgayThu = seedDate.AddDays(85), SoTienThu = 124869 },
                new PhieuThu { MaPhieuThu = 9, MaKhachHang = 3, NgayThu = seedDate.AddDays(107), SoTienThu = 6998 },
                new PhieuThu { MaPhieuThu = 10, MaKhachHang = 3, NgayThu = seedDate.AddDays(118), SoTienThu = 5780 },
                new PhieuThu { MaPhieuThu = 11, MaKhachHang = 3, NgayThu = seedDate.AddDays(133), SoTienThu = 27796 },
                new PhieuThu { MaPhieuThu = 12, MaKhachHang = 4, NgayThu = seedDate.AddDays(104), SoTienThu = 48321 },
                new PhieuThu { MaPhieuThu = 13, MaKhachHang = 4, NgayThu = seedDate.AddDays(134), SoTienThu = 61235 },
                new PhieuThu { MaPhieuThu = 14, MaKhachHang = 4, NgayThu = seedDate.AddDays(152), SoTienThu = 15795 },
                new PhieuThu { MaPhieuThu = 15, MaKhachHang = 5, NgayThu = seedDate.AddDays(75), SoTienThu = 84724 },
                new PhieuThu { MaPhieuThu = 16, MaKhachHang = 5, NgayThu = seedDate.AddDays(83), SoTienThu = 92575 },
                new PhieuThu { MaPhieuThu = 17, MaKhachHang = 5, NgayThu = seedDate.AddDays(96), SoTienThu = 1901 },
                new PhieuThu { MaPhieuThu = 18, MaKhachHang = 5, NgayThu = seedDate.AddDays(100), SoTienThu = 424 },
                new PhieuThu { MaPhieuThu = 19, MaKhachHang = 5, NgayThu = seedDate.AddDays(117), SoTienThu = 1205 },
                new PhieuThu { MaPhieuThu = 20, MaKhachHang = 6, NgayThu = seedDate.AddDays(53), SoTienThu = 134755 },
                new PhieuThu { MaPhieuThu = 21, MaKhachHang = 6, NgayThu = seedDate.AddDays(69), SoTienThu = 153 },
                new PhieuThu { MaPhieuThu = 22, MaKhachHang = 7, NgayThu = seedDate.AddDays(110), SoTienThu = 95005 },
                new PhieuThu { MaPhieuThu = 23, MaKhachHang = 7, NgayThu = seedDate.AddDays(132), SoTienThu = 116962 },
                new PhieuThu { MaPhieuThu = 24, MaKhachHang = 8, NgayThu = seedDate.AddDays(77), SoTienThu = 148873 },
                new PhieuThu { MaPhieuThu = 25, MaKhachHang = 8, NgayThu = seedDate.AddDays(98), SoTienThu = 16159 },
                new PhieuThu { MaPhieuThu = 26, MaKhachHang = 9, NgayThu = seedDate.AddDays(76), SoTienThu = 49579 },
                new PhieuThu { MaPhieuThu = 27, MaKhachHang = 9, NgayThu = seedDate.AddDays(96), SoTienThu = 140535 },
                new PhieuThu { MaPhieuThu = 28, MaKhachHang = 9, NgayThu = seedDate.AddDays(114), SoTienThu = 5540 },
                new PhieuThu { MaPhieuThu = 29, MaKhachHang = 10, NgayThu = seedDate.AddDays(40), SoTienThu = 7144 },
                new PhieuThu { MaPhieuThu = 30, MaKhachHang = 10, NgayThu = seedDate.AddDays(63), SoTienThu = 12135 },
                new PhieuThu { MaPhieuThu = 31, MaKhachHang = 10, NgayThu = seedDate.AddDays(72), SoTienThu = 3516 },
                new PhieuThu { MaPhieuThu = 32, MaKhachHang = 10, NgayThu = seedDate.AddDays(97), SoTienThu = 1220 }
            );
        }

        private static void SeedKhachHang(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<KhachHang>().HasData(
                new KhachHang
                {
                    MaKhachHang = 1,
                    TenKhachHang = "Nguyễn Anh Đặng",
                    DiaChi = "12 An Dương Vương",
                    DienThoai = "0912345678",
                    Email = "nguyenanhdang1@gmail.com",
                    TienNo = 15000L
                },
                new KhachHang
                {
                    MaKhachHang = 2,
                    TenKhachHang = "Trần Bích Hạnh",
                    DiaChi = "34 Bạch Đằng",
                    DienThoai = "0923456789",
                    Email = "tranbichhanh2@gmail.com",
                    TienNo = 20000L
                },
                new KhachHang
                {
                    MaKhachHang = 3,
                    TenKhachHang = "Lê Cường Minh",
                    DiaChi = "56 Cách Mạng Tháng 8",
                    DienThoai = "0934567890",
                    Email = "lecuongminh3@gmail.com",
                    TienNo = 17000L
                },
                new KhachHang
                {
                    MaKhachHang = 4,
                    TenKhachHang = "Ngô Dương Quang",
                    DiaChi = "78 Đặng Văn Ngữ",
                    DienThoai = "0945678901",
                    Email = "ngoduongquang4@gmail.com",
                    TienNo = 13000L
                },
                new KhachHang
                {
                    MaKhachHang = 5,
                    TenKhachHang = "Phạm Hà Vy",
                    DiaChi = "90 Hàn Thuyên",
                    DienThoai = "0956789012",
                    Email = "phamhavy5@gmail.com",
                    TienNo = 14000L
                },
                new KhachHang
                {
                    MaKhachHang = 6,
                    TenKhachHang = "Phan Hải Long",
                    DiaChi = "21 Hoàng Diệu",
                    DienThoai = "0967890123",
                    Email = "phanhailong6@gmail.com",
                    TienNo = 10000L
                },
                new KhachHang
                {
                    MaKhachHang = 7,
                    TenKhachHang = "Vũ Hương Giang",
                    DiaChi = "43 Huỳnh Thúc Kháng",
                    DienThoai = "0978901234",
                    Email = "vuhuonggiang7@gmail.com",
                    TienNo = 5000L
                },
                new KhachHang
                {
                    MaKhachHang = 8,
                    TenKhachHang = "Võ Khoa Nam",
                    DiaChi = "65 Kim Mã",
                    DienThoai = "0989012345",
                    Email = "vokhoanam8@gmail.com",
                    TienNo = 12000L
                },
                new KhachHang
                {
                    MaKhachHang = 9,
                    TenKhachHang = "Trần Linh Chi",
                    DiaChi = "87 Lê Lợi",
                    DienThoai = "0990123456",
                    Email = "tranlinhchi9@gmail.com",
                    TienNo = 25000L
                },
                new KhachHang
                {
                    MaKhachHang = 10,
                    TenKhachHang = "Phạm Minh Tuấn",
                    DiaChi = "109 Nguyễn Huệ",
                    DienThoai = "0901234567",
                    Email = "phamminhtuan10@gmail.com",
                    TienNo = 30000L
                }
            );
        }

        private static void SeedChiTietHoaDon(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ChiTietHoaDon>().HasData(
                new ChiTietHoaDon { MaChiTietHoaDon = 1, MaHoaDon = 1, MaSach = 22, SoLuongBan = 52, DonGiaBan = 89, ThanhTien = 4628 },
                new ChiTietHoaDon { MaChiTietHoaDon = 2, MaHoaDon = 1, MaSach = 15, SoLuongBan = 56, DonGiaBan = 109, ThanhTien = 6104 },
                new ChiTietHoaDon { MaChiTietHoaDon = 3, MaHoaDon = 2, MaSach = 25, SoLuongBan = 155, DonGiaBan = 146, ThanhTien = 22630 },
                new ChiTietHoaDon { MaChiTietHoaDon = 4, MaHoaDon = 2, MaSach = 30, SoLuongBan = 93, DonGiaBan = 121, ThanhTien = 11253 },
                new ChiTietHoaDon { MaChiTietHoaDon = 5, MaHoaDon = 2, MaSach = 5, SoLuongBan = 108, DonGiaBan = 88, ThanhTien = 9504 },
                new ChiTietHoaDon { MaChiTietHoaDon = 6, MaHoaDon = 2, MaSach = 3, SoLuongBan = 133, DonGiaBan = 91, ThanhTien = 12103 },
                new ChiTietHoaDon { MaChiTietHoaDon = 7, MaHoaDon = 2, MaSach = 9, SoLuongBan = 119, DonGiaBan = 97, ThanhTien = 11543 },
                new ChiTietHoaDon { MaChiTietHoaDon = 8, MaHoaDon = 3, MaSach = 10, SoLuongBan = 64, DonGiaBan = 122, ThanhTien = 7808 },
                new ChiTietHoaDon { MaChiTietHoaDon = 9, MaHoaDon = 3, MaSach = 25, SoLuongBan = 101, DonGiaBan = 150, ThanhTien = 15150 },
                new ChiTietHoaDon { MaChiTietHoaDon = 10, MaHoaDon = 3, MaSach = 5, SoLuongBan = 84, DonGiaBan = 117, ThanhTien = 9828 },
                new ChiTietHoaDon { MaChiTietHoaDon = 11, MaHoaDon = 4, MaSach = 15, SoLuongBan = 174, DonGiaBan = 97, ThanhTien = 16878 },
                new ChiTietHoaDon { MaChiTietHoaDon = 12, MaHoaDon = 4, MaSach = 26, SoLuongBan = 41, DonGiaBan = 133, ThanhTien = 5453 },
                new ChiTietHoaDon { MaChiTietHoaDon = 13, MaHoaDon = 4, MaSach = 21, SoLuongBan = 96, DonGiaBan = 118, ThanhTien = 11328 },
                new ChiTietHoaDon { MaChiTietHoaDon = 14, MaHoaDon = 4, MaSach = 2, SoLuongBan = 103, DonGiaBan = 121, ThanhTien = 12463 },
                new ChiTietHoaDon { MaChiTietHoaDon = 15, MaHoaDon = 5, MaSach = 20, SoLuongBan = 100, DonGiaBan = 144, ThanhTien = 14400 },
                new ChiTietHoaDon { MaChiTietHoaDon = 16, MaHoaDon = 5, MaSach = 19, SoLuongBan = 104, DonGiaBan = 100, ThanhTien = 10400 },
                new ChiTietHoaDon { MaChiTietHoaDon = 17, MaHoaDon = 6, MaSach = 6, SoLuongBan = 168, DonGiaBan = 110, ThanhTien = 18480 },
                new ChiTietHoaDon { MaChiTietHoaDon = 18, MaHoaDon = 6, MaSach = 10, SoLuongBan = 196, DonGiaBan = 109, ThanhTien = 21364 },
                new ChiTietHoaDon { MaChiTietHoaDon = 19, MaHoaDon = 7, MaSach = 20, SoLuongBan = 37, DonGiaBan = 106, ThanhTien = 3922 },
                new ChiTietHoaDon { MaChiTietHoaDon = 20, MaHoaDon = 7, MaSach = 26, SoLuongBan = 67, DonGiaBan = 101, ThanhTien = 6767 },
                new ChiTietHoaDon { MaChiTietHoaDon = 21, MaHoaDon = 7, MaSach = 7, SoLuongBan = 45, DonGiaBan = 95, ThanhTien = 4275 },
                new ChiTietHoaDon { MaChiTietHoaDon = 22, MaHoaDon = 7, MaSach = 14, SoLuongBan = 108, DonGiaBan = 127, ThanhTien = 13716 },
                new ChiTietHoaDon { MaChiTietHoaDon = 23, MaHoaDon = 8, MaSach = 4, SoLuongBan = 159, DonGiaBan = 102, ThanhTien = 16218 },
                new ChiTietHoaDon { MaChiTietHoaDon = 24, MaHoaDon = 8, MaSach = 25, SoLuongBan = 53, DonGiaBan = 72, ThanhTien = 3816 },
                new ChiTietHoaDon { MaChiTietHoaDon = 25, MaHoaDon = 8, MaSach = 20, SoLuongBan = 115, DonGiaBan = 125, ThanhTien = 14375 },
                new ChiTietHoaDon { MaChiTietHoaDon = 26, MaHoaDon = 8, MaSach = 8, SoLuongBan = 82, DonGiaBan = 117, ThanhTien = 9594 },
                new ChiTietHoaDon { MaChiTietHoaDon = 27, MaHoaDon = 8, MaSach = 17, SoLuongBan = 125, DonGiaBan = 114, ThanhTien = 14250 },
                new ChiTietHoaDon { MaChiTietHoaDon = 28, MaHoaDon = 9, MaSach = 14, SoLuongBan = 125, DonGiaBan = 116, ThanhTien = 14500 },
                new ChiTietHoaDon { MaChiTietHoaDon = 29, MaHoaDon = 9, MaSach = 10, SoLuongBan = 198, DonGiaBan = 138, ThanhTien = 27324 },
                new ChiTietHoaDon { MaChiTietHoaDon = 30, MaHoaDon = 9, MaSach = 22, SoLuongBan = 195, DonGiaBan = 125, ThanhTien = 24375 },
                new ChiTietHoaDon { MaChiTietHoaDon = 31, MaHoaDon = 10, MaSach = 1, SoLuongBan = 94, DonGiaBan = 146, ThanhTien = 13724 },
                new ChiTietHoaDon { MaChiTietHoaDon = 32, MaHoaDon = 10, MaSach = 2, SoLuongBan = 143, DonGiaBan = 112, ThanhTien = 16016 },
                new ChiTietHoaDon { MaChiTietHoaDon = 33, MaHoaDon = 10, MaSach = 12, SoLuongBan = 41, DonGiaBan = 103, ThanhTien = 4223 },
                new ChiTietHoaDon { MaChiTietHoaDon = 34, MaHoaDon = 11, MaSach = 4, SoLuongBan = 126, DonGiaBan = 122, ThanhTien = 15372 },
                new ChiTietHoaDon { MaChiTietHoaDon = 35, MaHoaDon = 11, MaSach = 23, SoLuongBan = 80, DonGiaBan = 97, ThanhTien = 7760 },
                new ChiTietHoaDon { MaChiTietHoaDon = 36, MaHoaDon = 11, MaSach = 15, SoLuongBan = 98, DonGiaBan = 107, ThanhTien = 10486 },
                new ChiTietHoaDon { MaChiTietHoaDon = 37, MaHoaDon = 11, MaSach = 22, SoLuongBan = 138, DonGiaBan = 122, ThanhTien = 16836 },
                new ChiTietHoaDon { MaChiTietHoaDon = 38, MaHoaDon = 11, MaSach = 29, SoLuongBan = 199, DonGiaBan = 129, ThanhTien = 25671 },
                new ChiTietHoaDon { MaChiTietHoaDon = 39, MaHoaDon = 12, MaSach = 2, SoLuongBan = 54, DonGiaBan = 114, ThanhTien = 6156 },
                new ChiTietHoaDon { MaChiTietHoaDon = 40, MaHoaDon = 13, MaSach = 13, SoLuongBan = 127, DonGiaBan = 118, ThanhTien = 14986 },
                new ChiTietHoaDon { MaChiTietHoaDon = 41, MaHoaDon = 13, MaSach = 16, SoLuongBan = 99, DonGiaBan = 135, ThanhTien = 13365 },
                new ChiTietHoaDon { MaChiTietHoaDon = 42, MaHoaDon = 13, MaSach = 11, SoLuongBan = 85, DonGiaBan = 91, ThanhTien = 7735 },
                new ChiTietHoaDon { MaChiTietHoaDon = 43, MaHoaDon = 13, MaSach = 15, SoLuongBan = 95, DonGiaBan = 95, ThanhTien = 9025 },
                new ChiTietHoaDon { MaChiTietHoaDon = 44, MaHoaDon = 14, MaSach = 26, SoLuongBan = 152, DonGiaBan = 146, ThanhTien = 22192 },
                new ChiTietHoaDon { MaChiTietHoaDon = 45, MaHoaDon = 15, MaSach = 2, SoLuongBan = 40, DonGiaBan = 148, ThanhTien = 5920 },
                new ChiTietHoaDon { MaChiTietHoaDon = 46, MaHoaDon = 15, MaSach = 23, SoLuongBan = 167, DonGiaBan = 102, ThanhTien = 17034 },
                new ChiTietHoaDon { MaChiTietHoaDon = 47, MaHoaDon = 15, MaSach = 3, SoLuongBan = 145, DonGiaBan = 80, ThanhTien = 11600 },
                new ChiTietHoaDon { MaChiTietHoaDon = 48, MaHoaDon = 16, MaSach = 8, SoLuongBan = 118, DonGiaBan = 93, ThanhTien = 10974 },
                new ChiTietHoaDon { MaChiTietHoaDon = 49, MaHoaDon = 17, MaSach = 1, SoLuongBan = 176, DonGiaBan = 145, ThanhTien = 25520 },
                new ChiTietHoaDon { MaChiTietHoaDon = 50, MaHoaDon = 18, MaSach = 28, SoLuongBan = 187, DonGiaBan = 139, ThanhTien = 25993 },
                new ChiTietHoaDon { MaChiTietHoaDon = 51, MaHoaDon = 18, MaSach = 9, SoLuongBan = 184, DonGiaBan = 92, ThanhTien = 16928 },
                new ChiTietHoaDon { MaChiTietHoaDon = 52, MaHoaDon = 18, MaSach = 26, SoLuongBan = 61, DonGiaBan = 107, ThanhTien = 6527 },
                new ChiTietHoaDon { MaChiTietHoaDon = 53, MaHoaDon = 18, MaSach = 29, SoLuongBan = 176, DonGiaBan = 75, ThanhTien = 13200 },
                new ChiTietHoaDon { MaChiTietHoaDon = 54, MaHoaDon = 19, MaSach = 13, SoLuongBan = 37, DonGiaBan = 89, ThanhTien = 3293 },
                new ChiTietHoaDon { MaChiTietHoaDon = 55, MaHoaDon = 19, MaSach = 25, SoLuongBan = 72, DonGiaBan = 132, ThanhTien = 9504 },
                new ChiTietHoaDon { MaChiTietHoaDon = 56, MaHoaDon = 19, MaSach = 3, SoLuongBan = 97, DonGiaBan = 91, ThanhTien = 8827 },
                new ChiTietHoaDon { MaChiTietHoaDon = 57, MaHoaDon = 19, MaSach = 24, SoLuongBan = 96, DonGiaBan = 117, ThanhTien = 11232 },
                new ChiTietHoaDon { MaChiTietHoaDon = 58, MaHoaDon = 19, MaSach = 12, SoLuongBan = 109, DonGiaBan = 135, ThanhTien = 14715 },
                new ChiTietHoaDon { MaChiTietHoaDon = 59, MaHoaDon = 20, MaSach = 3, SoLuongBan = 182, DonGiaBan = 85, ThanhTien = 15470 },
                new ChiTietHoaDon { MaChiTietHoaDon = 60, MaHoaDon = 20, MaSach = 1, SoLuongBan = 80, DonGiaBan = 140, ThanhTien = 11200 },
                new ChiTietHoaDon { MaChiTietHoaDon = 61, MaHoaDon = 20, MaSach = 15, SoLuongBan = 178, DonGiaBan = 92, ThanhTien = 16376 },
                new ChiTietHoaDon { MaChiTietHoaDon = 62, MaHoaDon = 20, MaSach = 11, SoLuongBan = 161, DonGiaBan = 122, ThanhTien = 19642 },
                new ChiTietHoaDon { MaChiTietHoaDon = 63, MaHoaDon = 20, MaSach = 26, SoLuongBan = 187, DonGiaBan = 85, ThanhTien = 15895 },
                new ChiTietHoaDon { MaChiTietHoaDon = 64, MaHoaDon = 21, MaSach = 27, SoLuongBan = 41, DonGiaBan = 147, ThanhTien = 6027 },
                new ChiTietHoaDon { MaChiTietHoaDon = 65, MaHoaDon = 22, MaSach = 7, SoLuongBan = 74, DonGiaBan = 98, ThanhTien = 7252 },
                new ChiTietHoaDon { MaChiTietHoaDon = 66, MaHoaDon = 22, MaSach = 19, SoLuongBan = 63, DonGiaBan = 110, ThanhTien = 6930 },
                new ChiTietHoaDon { MaChiTietHoaDon = 67, MaHoaDon = 22, MaSach = 4, SoLuongBan = 192, DonGiaBan = 72, ThanhTien = 13824 },
                new ChiTietHoaDon { MaChiTietHoaDon = 68, MaHoaDon = 22, MaSach = 21, SoLuongBan = 97, DonGiaBan = 139, ThanhTien = 13483 },
                new ChiTietHoaDon { MaChiTietHoaDon = 69, MaHoaDon = 23, MaSach = 15, SoLuongBan = 154, DonGiaBan = 127, ThanhTien = 19558 },
                new ChiTietHoaDon { MaChiTietHoaDon = 70, MaHoaDon = 23, MaSach = 3, SoLuongBan = 70, DonGiaBan = 126, ThanhTien = 8820 },
                new ChiTietHoaDon { MaChiTietHoaDon = 71, MaHoaDon = 23, MaSach = 29, SoLuongBan = 193, DonGiaBan = 82, ThanhTien = 15826 },
                new ChiTietHoaDon { MaChiTietHoaDon = 72, MaHoaDon = 23, MaSach = 20, SoLuongBan = 111, DonGiaBan = 73, ThanhTien = 8103 },
                new ChiTietHoaDon { MaChiTietHoaDon = 73, MaHoaDon = 24, MaSach = 29, SoLuongBan = 104, DonGiaBan = 74, ThanhTien = 7696 },
                new ChiTietHoaDon { MaChiTietHoaDon = 74, MaHoaDon = 24, MaSach = 16, SoLuongBan = 137, DonGiaBan = 96, ThanhTien = 13152 },
                new ChiTietHoaDon { MaChiTietHoaDon = 75, MaHoaDon = 25, MaSach = 21, SoLuongBan = 169, DonGiaBan = 148, ThanhTien = 25012 },
                new ChiTietHoaDon { MaChiTietHoaDon = 76, MaHoaDon = 25, MaSach = 30, SoLuongBan = 52, DonGiaBan = 101, ThanhTien = 5252 },
                new ChiTietHoaDon { MaChiTietHoaDon = 77, MaHoaDon = 26, MaSach = 7, SoLuongBan = 103, DonGiaBan = 149, ThanhTien = 15347 },
                new ChiTietHoaDon { MaChiTietHoaDon = 78, MaHoaDon = 26, MaSach = 15, SoLuongBan = 70, DonGiaBan = 125, ThanhTien = 8750 },
                new ChiTietHoaDon { MaChiTietHoaDon = 79, MaHoaDon = 27, MaSach = 2, SoLuongBan = 117, DonGiaBan = 150, ThanhTien = 17550 },
                new ChiTietHoaDon { MaChiTietHoaDon = 80, MaHoaDon = 27, MaSach = 21, SoLuongBan = 108, DonGiaBan = 73, ThanhTien = 7884 },
                new ChiTietHoaDon { MaChiTietHoaDon = 81, MaHoaDon = 27, MaSach = 17, SoLuongBan = 37, DonGiaBan = 107, ThanhTien = 3959 },
                new ChiTietHoaDon { MaChiTietHoaDon = 82, MaHoaDon = 27, MaSach = 16, SoLuongBan = 188, DonGiaBan = 120, ThanhTien = 22560 },
                new ChiTietHoaDon { MaChiTietHoaDon = 83, MaHoaDon = 27, MaSach = 12, SoLuongBan = 116, DonGiaBan = 132, ThanhTien = 15312 },
                new ChiTietHoaDon { MaChiTietHoaDon = 84, MaHoaDon = 28, MaSach = 15, SoLuongBan = 39, DonGiaBan = 140, ThanhTien = 5460 },
                new ChiTietHoaDon { MaChiTietHoaDon = 85, MaHoaDon = 28, MaSach = 4, SoLuongBan = 66, DonGiaBan = 74, ThanhTien = 4884 },
                new ChiTietHoaDon { MaChiTietHoaDon = 86, MaHoaDon = 29, MaSach = 14, SoLuongBan = 151, DonGiaBan = 124, ThanhTien = 18724 },
                new ChiTietHoaDon { MaChiTietHoaDon = 87, MaHoaDon = 29, MaSach = 16, SoLuongBan = 36, DonGiaBan = 93, ThanhTien = 3348 },
                new ChiTietHoaDon { MaChiTietHoaDon = 88, MaHoaDon = 29, MaSach = 18, SoLuongBan = 123, DonGiaBan = 111, ThanhTien = 13653 },
                new ChiTietHoaDon { MaChiTietHoaDon = 89, MaHoaDon = 30, MaSach = 1, SoLuongBan = 179, DonGiaBan = 88, ThanhTien = 15752 },
                new ChiTietHoaDon { MaChiTietHoaDon = 90, MaHoaDon = 30, MaSach = 7, SoLuongBan = 192, DonGiaBan = 142, ThanhTien = 27264 },
                new ChiTietHoaDon { MaChiTietHoaDon = 91, MaHoaDon = 30, MaSach = 11, SoLuongBan = 180, DonGiaBan = 82, ThanhTien = 14760 },
                new ChiTietHoaDon { MaChiTietHoaDon = 92, MaHoaDon = 30, MaSach = 22, SoLuongBan = 56, DonGiaBan = 144, ThanhTien = 8064 },
                new ChiTietHoaDon { MaChiTietHoaDon = 93, MaHoaDon = 30, MaSach = 6, SoLuongBan = 128, DonGiaBan = 107, ThanhTien = 13696 },
                new ChiTietHoaDon { MaChiTietHoaDon = 94, MaHoaDon = 31, MaSach = 21, SoLuongBan = 175, DonGiaBan = 140, ThanhTien = 24500 },
                new ChiTietHoaDon { MaChiTietHoaDon = 95, MaHoaDon = 31, MaSach = 4, SoLuongBan = 108, DonGiaBan = 120, ThanhTien = 12960 },
                new ChiTietHoaDon { MaChiTietHoaDon = 96, MaHoaDon = 31, MaSach = 3, SoLuongBan = 91, DonGiaBan = 147, ThanhTien = 13377 },
                new ChiTietHoaDon { MaChiTietHoaDon = 97, MaHoaDon = 32, MaSach = 15, SoLuongBan = 161, DonGiaBan = 100, ThanhTien = 16100 },
                new ChiTietHoaDon { MaChiTietHoaDon = 98, MaHoaDon = 32, MaSach = 13, SoLuongBan = 122, DonGiaBan = 144, ThanhTien = 17568 },
                new ChiTietHoaDon { MaChiTietHoaDon = 99, MaHoaDon = 32, MaSach = 7, SoLuongBan = 117, DonGiaBan = 86, ThanhTien = 10062 },
                new ChiTietHoaDon { MaChiTietHoaDon = 100, MaHoaDon = 32, MaSach = 26, SoLuongBan = 141, DonGiaBan = 116, ThanhTien = 16356 },
                new ChiTietHoaDon { MaChiTietHoaDon = 101, MaHoaDon = 33, MaSach = 3, SoLuongBan = 179, DonGiaBan = 90, ThanhTien = 16110 },
                new ChiTietHoaDon { MaChiTietHoaDon = 102, MaHoaDon = 33, MaSach = 18, SoLuongBan = 61, DonGiaBan = 142, ThanhTien = 8662 },
                new ChiTietHoaDon { MaChiTietHoaDon = 103, MaHoaDon = 33, MaSach = 27, SoLuongBan = 96, DonGiaBan = 132, ThanhTien = 12672 },
                new ChiTietHoaDon { MaChiTietHoaDon = 104, MaHoaDon = 33, MaSach = 15, SoLuongBan = 195, DonGiaBan = 147, ThanhTien = 28665 },
                new ChiTietHoaDon { MaChiTietHoaDon = 105, MaHoaDon = 34, MaSach = 9, SoLuongBan = 177, DonGiaBan = 135, ThanhTien = 23895 },
                new ChiTietHoaDon { MaChiTietHoaDon = 106, MaHoaDon = 34, MaSach = 29, SoLuongBan = 63, DonGiaBan = 112, ThanhTien = 7056 },
                new ChiTietHoaDon { MaChiTietHoaDon = 107, MaHoaDon = 34, MaSach = 3, SoLuongBan = 104, DonGiaBan = 144, ThanhTien = 14976 },
                new ChiTietHoaDon { MaChiTietHoaDon = 108, MaHoaDon = 35, MaSach = 25, SoLuongBan = 68, DonGiaBan = 141, ThanhTien = 9588 },
                new ChiTietHoaDon { MaChiTietHoaDon = 109, MaHoaDon = 35, MaSach = 1, SoLuongBan = 154, DonGiaBan = 108, ThanhTien = 16632 },
                new ChiTietHoaDon { MaChiTietHoaDon = 110, MaHoaDon = 35, MaSach = 5, SoLuongBan = 82, DonGiaBan = 136, ThanhTien = 11152 },
                new ChiTietHoaDon { MaChiTietHoaDon = 111, MaHoaDon = 35, MaSach = 15, SoLuongBan = 107, DonGiaBan = 133, ThanhTien = 14231 },
                new ChiTietHoaDon { MaChiTietHoaDon = 112, MaHoaDon = 36, MaSach = 11, SoLuongBan = 122, DonGiaBan = 91, ThanhTien = 11102 },
                new ChiTietHoaDon { MaChiTietHoaDon = 113, MaHoaDon = 36, MaSach = 6, SoLuongBan = 109, DonGiaBan = 101, ThanhTien = 11009 },
                new ChiTietHoaDon { MaChiTietHoaDon = 114, MaHoaDon = 36, MaSach = 5, SoLuongBan = 106, DonGiaBan = 99, ThanhTien = 10494 },
                new ChiTietHoaDon { MaChiTietHoaDon = 115, MaHoaDon = 36, MaSach = 18, SoLuongBan = 146, DonGiaBan = 75, ThanhTien = 10950 },
                new ChiTietHoaDon { MaChiTietHoaDon = 116, MaHoaDon = 36, MaSach = 20, SoLuongBan = 87, DonGiaBan = 145, ThanhTien = 12615 },
                new ChiTietHoaDon { MaChiTietHoaDon = 117, MaHoaDon = 37, MaSach = 25, SoLuongBan = 198, DonGiaBan = 136, ThanhTien = 26928 },
                new ChiTietHoaDon { MaChiTietHoaDon = 118, MaHoaDon = 37, MaSach = 3, SoLuongBan = 142, DonGiaBan = 81, ThanhTien = 11502 },
                new ChiTietHoaDon { MaChiTietHoaDon = 119, MaHoaDon = 38, MaSach = 23, SoLuongBan = 150, DonGiaBan = 140, ThanhTien = 21000 },
                new ChiTietHoaDon { MaChiTietHoaDon = 120, MaHoaDon = 38, MaSach = 2, SoLuongBan = 66, DonGiaBan = 114, ThanhTien = 7524 },
                new ChiTietHoaDon { MaChiTietHoaDon = 121, MaHoaDon = 39, MaSach = 19, SoLuongBan = 66, DonGiaBan = 92, ThanhTien = 6072 },
                new ChiTietHoaDon { MaChiTietHoaDon = 122, MaHoaDon = 39, MaSach = 22, SoLuongBan = 91, DonGiaBan = 131, ThanhTien = 11921 },
                new ChiTietHoaDon { MaChiTietHoaDon = 123, MaHoaDon = 39, MaSach = 11, SoLuongBan = 87, DonGiaBan = 97, ThanhTien = 8439 },
                new ChiTietHoaDon { MaChiTietHoaDon = 124, MaHoaDon = 39, MaSach = 30, SoLuongBan = 76, DonGiaBan = 142, ThanhTien = 10792 },
                new ChiTietHoaDon { MaChiTietHoaDon = 125, MaHoaDon = 39, MaSach = 9, SoLuongBan = 31, DonGiaBan = 79, ThanhTien = 2449 },
                new ChiTietHoaDon { MaChiTietHoaDon = 126, MaHoaDon = 40, MaSach = 6, SoLuongBan = 101, DonGiaBan = 142, ThanhTien = 14342 }
            );
        }
        private static void SeedHoaDonBanSach(ModelBuilder modelBuilder)
        {
            var seedDate = new DateTime(2023, 1, 1);

            modelBuilder.Entity<HoaDon>().HasData(
                new HoaDon { MaHoaDon = 1, MaKhachHang = 1, NgayLap = seedDate.AddDays(21), TongTien = 10732 },
                new HoaDon { MaHoaDon = 2, MaKhachHang = 1, NgayLap = seedDate.AddDays(30), TongTien = 67033 },
                new HoaDon { MaHoaDon = 3, MaKhachHang = 1, NgayLap = seedDate.AddDays(41), TongTien = 32786 },
                new HoaDon { MaHoaDon = 4, MaKhachHang = 1, NgayLap = seedDate.AddDays(65), TongTien = 46122 },
                new HoaDon { MaHoaDon = 5, MaKhachHang = 1, NgayLap = seedDate.AddDays(74), TongTien = 24800 },
                new HoaDon { MaHoaDon = 6, MaKhachHang = 2, NgayLap = seedDate.AddDays(22), TongTien = 39844 },
                new HoaDon { MaHoaDon = 7, MaKhachHang = 2, NgayLap = seedDate.AddDays(40), TongTien = 28680 },
                new HoaDon { MaHoaDon = 8, MaKhachHang = 2, NgayLap = seedDate.AddDays(69), TongTien = 58253 },
                new HoaDon { MaHoaDon = 9, MaKhachHang = 3, NgayLap = seedDate.AddDays(18), TongTien = 66199 },
                new HoaDon { MaHoaDon = 10, MaKhachHang = 3, NgayLap = seedDate.AddDays(29), TongTien = 33963 },
                new HoaDon { MaHoaDon = 11, MaKhachHang = 3, NgayLap = seedDate.AddDays(47), TongTien = 76125 },
                new HoaDon { MaHoaDon = 12, MaKhachHang = 3, NgayLap = seedDate.AddDays(74), TongTien = 6156 },
                new HoaDon { MaHoaDon = 13, MaKhachHang = 4, NgayLap = seedDate.AddDays(28), TongTien = 45111 },
                new HoaDon { MaHoaDon = 14, MaKhachHang = 4, NgayLap = seedDate.AddDays(58), TongTien = 22192 },
                new HoaDon { MaHoaDon = 15, MaKhachHang = 4, NgayLap = seedDate.AddDays(75), TongTien = 34554 },
                new HoaDon { MaHoaDon = 16, MaKhachHang = 4, NgayLap = seedDate.AddDays(93), TongTien = 10974 },
                new HoaDon { MaHoaDon = 17, MaKhachHang = 4, NgayLap = seedDate.AddDays(98), TongTien = 25520 },
                new HoaDon { MaHoaDon = 18, MaKhachHang = 5, NgayLap = seedDate.AddDays(4), TongTien = 62648 },
                new HoaDon { MaHoaDon = 19, MaKhachHang = 5, NgayLap = seedDate.AddDays(18), TongTien = 47571 },
                new HoaDon { MaHoaDon = 20, MaKhachHang = 5, NgayLap = seedDate.AddDays(21), TongTien = 78583 },
                new HoaDon { MaHoaDon = 21, MaKhachHang = 5, NgayLap = seedDate.AddDays(47), TongTien = 6027 },
                new HoaDon { MaHoaDon = 22, MaKhachHang = 6, NgayLap = seedDate.AddDays(30), TongTien = 41489 },
                new HoaDon { MaHoaDon = 23, MaKhachHang = 6, NgayLap = seedDate.AddDays(40), TongTien = 52307 },
                new HoaDon { MaHoaDon = 24, MaKhachHang = 6, NgayLap = seedDate.AddDays(47), TongTien = 20848 },
                new HoaDon { MaHoaDon = 25, MaKhachHang = 6, NgayLap = seedDate.AddDays(50), TongTien = 30264 },
                new HoaDon { MaHoaDon = 26, MaKhachHang = 7, NgayLap = seedDate.AddDays(19), TongTien = 24097 },
                new HoaDon { MaHoaDon = 27, MaKhachHang = 7, NgayLap = seedDate.AddDays(23), TongTien = 67265 },
                new HoaDon { MaHoaDon = 28, MaKhachHang = 7, NgayLap = seedDate.AddDays(47), TongTien = 10344 },
                new HoaDon { MaHoaDon = 29, MaKhachHang = 7, NgayLap = seedDate.AddDays(76), TongTien = 35725 },
                new HoaDon { MaHoaDon = 30, MaKhachHang = 7, NgayLap = seedDate.AddDays(86), TongTien = 79536 },
                new HoaDon { MaHoaDon = 31, MaKhachHang = 8, NgayLap = seedDate.AddDays(30), TongTien = 50837 },
                new HoaDon { MaHoaDon = 32, MaKhachHang = 8, NgayLap = seedDate.AddDays(46), TongTien = 60086 },
                new HoaDon { MaHoaDon = 33, MaKhachHang = 8, NgayLap = seedDate.AddDays(63), TongTien = 66109 },
                new HoaDon { MaHoaDon = 34, MaKhachHang = 9, NgayLap = seedDate.AddDays(24), TongTien = 45927 },
                new HoaDon { MaHoaDon = 35, MaKhachHang = 9, NgayLap = seedDate.AddDays(32), TongTien = 51603 },
                new HoaDon { MaHoaDon = 36, MaKhachHang = 9, NgayLap = seedDate.AddDays(38), TongTien = 56170 },
                new HoaDon { MaHoaDon = 37, MaKhachHang = 9, NgayLap = seedDate.AddDays(50), TongTien = 38430 },
                new HoaDon { MaHoaDon = 38, MaKhachHang = 9, NgayLap = seedDate.AddDays(69), TongTien = 28524 },
                new HoaDon { MaHoaDon = 39, MaKhachHang = 10, NgayLap = seedDate.AddDays(14), TongTien = 39673 },
                new HoaDon { MaHoaDon = 40, MaKhachHang = 10, NgayLap = seedDate.AddDays(18), TongTien = 14342 }
            );
        }

        private static void SeedPhieuNhapSach(ModelBuilder modelBuilder)
        {
            var seedDate = new DateTime(2022, 1, 1);
            modelBuilder.Entity<PhieuNhapSach>().HasData(
                new PhieuNhapSach { MaPhieuNhapSach = 1, NgayNhap = seedDate.AddDays(8) },
                 new PhieuNhapSach { MaPhieuNhapSach = 2, NgayNhap = seedDate.AddDays(16) },
                 new PhieuNhapSach { MaPhieuNhapSach = 3, NgayNhap = seedDate.AddDays(23) },
                 new PhieuNhapSach { MaPhieuNhapSach = 4, NgayNhap = seedDate.AddDays(34) },
                 new PhieuNhapSach { MaPhieuNhapSach = 5, NgayNhap = seedDate.AddDays(53) },
                 new PhieuNhapSach { MaPhieuNhapSach = 6, NgayNhap = seedDate.AddDays(68) },
                 new PhieuNhapSach { MaPhieuNhapSach = 7, NgayNhap = seedDate.AddDays(82) },
                 new PhieuNhapSach { MaPhieuNhapSach = 8, NgayNhap = seedDate.AddDays(101) },
                 new PhieuNhapSach { MaPhieuNhapSach = 9, NgayNhap = seedDate.AddDays(108) },
                 new PhieuNhapSach { MaPhieuNhapSach = 10, NgayNhap = seedDate.AddDays(123) },
                 new PhieuNhapSach { MaPhieuNhapSach = 11, NgayNhap = seedDate.AddDays(143) },
                 new PhieuNhapSach { MaPhieuNhapSach = 12, NgayNhap = seedDate.AddDays(162) },
                 new PhieuNhapSach { MaPhieuNhapSach = 13, NgayNhap = seedDate.AddDays(182) },
                 new PhieuNhapSach { MaPhieuNhapSach = 14, NgayNhap = seedDate.AddDays(191) },
                 new PhieuNhapSach { MaPhieuNhapSach = 15, NgayNhap = seedDate.AddDays(207) },
                 new PhieuNhapSach { MaPhieuNhapSach = 16, NgayNhap = seedDate.AddDays(227) },
                 new PhieuNhapSach { MaPhieuNhapSach = 17, NgayNhap = seedDate.AddDays(230) },
                 new PhieuNhapSach { MaPhieuNhapSach = 18, NgayNhap = seedDate.AddDays(241) },
                 new PhieuNhapSach { MaPhieuNhapSach = 19, NgayNhap = seedDate.AddDays(251) },
                 new PhieuNhapSach { MaPhieuNhapSach = 20, NgayNhap = seedDate.AddDays(271) },
                 new PhieuNhapSach { MaPhieuNhapSach = 21, NgayNhap = seedDate.AddDays(276) },
                 new PhieuNhapSach { MaPhieuNhapSach = 22, NgayNhap = seedDate.AddDays(295) },
                 new PhieuNhapSach { MaPhieuNhapSach = 23, NgayNhap = seedDate.AddDays(315) },
                 new PhieuNhapSach { MaPhieuNhapSach = 24, NgayNhap = seedDate.AddDays(324) },
                 new PhieuNhapSach { MaPhieuNhapSach = 25, NgayNhap = seedDate.AddDays(341) },
                 new PhieuNhapSach { MaPhieuNhapSach = 26, NgayNhap = seedDate.AddDays(361) },
                 new PhieuNhapSach { MaPhieuNhapSach = 27, NgayNhap = seedDate.AddDays(373) },
                 new PhieuNhapSach { MaPhieuNhapSach = 28, NgayNhap = seedDate.AddDays(391) },
                 new PhieuNhapSach { MaPhieuNhapSach = 29, NgayNhap = seedDate.AddDays(396) },
                 new PhieuNhapSach { MaPhieuNhapSach = 30, NgayNhap = seedDate.AddDays(411) },
                 new PhieuNhapSach { MaPhieuNhapSach = 31, NgayNhap = seedDate.AddDays(416) },
                 new PhieuNhapSach { MaPhieuNhapSach = 32, NgayNhap = seedDate.AddDays(419) },
                 new PhieuNhapSach { MaPhieuNhapSach = 33, NgayNhap = seedDate.AddDays(439) },
                 new PhieuNhapSach { MaPhieuNhapSach = 34, NgayNhap = seedDate.AddDays(440) },
                 new PhieuNhapSach { MaPhieuNhapSach = 35, NgayNhap = seedDate.AddDays(457) },
                 new PhieuNhapSach { MaPhieuNhapSach = 36, NgayNhap = seedDate.AddDays(466) },
                 new PhieuNhapSach { MaPhieuNhapSach = 37, NgayNhap = seedDate.AddDays(475) },
                 new PhieuNhapSach { MaPhieuNhapSach = 38, NgayNhap = seedDate.AddDays(478) },
                 new PhieuNhapSach { MaPhieuNhapSach = 39, NgayNhap = seedDate.AddDays(492) },
                 new PhieuNhapSach { MaPhieuNhapSach = 40, NgayNhap = seedDate.AddDays(500) },
                 new PhieuNhapSach { MaPhieuNhapSach = 41, NgayNhap = seedDate.AddDays(515) },
                 new PhieuNhapSach { MaPhieuNhapSach = 42, NgayNhap = seedDate.AddDays(521) },
                 new PhieuNhapSach { MaPhieuNhapSach = 43, NgayNhap = seedDate.AddDays(525) },
                 new PhieuNhapSach { MaPhieuNhapSach = 44, NgayNhap = seedDate.AddDays(528) },
                 new PhieuNhapSach { MaPhieuNhapSach = 45, NgayNhap = seedDate.AddDays(543) },
                 new PhieuNhapSach { MaPhieuNhapSach = 46, NgayNhap = seedDate.AddDays(545) },
                 new PhieuNhapSach { MaPhieuNhapSach = 47, NgayNhap = seedDate.AddDays(553) },
                 new PhieuNhapSach { MaPhieuNhapSach = 48, NgayNhap = seedDate.AddDays(554) },
                 new PhieuNhapSach { MaPhieuNhapSach = 49, NgayNhap = seedDate.AddDays(573) },
                 new PhieuNhapSach { MaPhieuNhapSach = 50, NgayNhap = seedDate.AddDays(581) }
            );
        }

        private static void SeedChiTietPhieuNhap(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ChiTietPhieuNhap>().HasData(
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 1, MaPhieuNhapSach = 1, MaSach = 1, SoLuongNhap = 101 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 2, MaPhieuNhapSach = 1, MaSach = 18, SoLuongNhap = 88 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 3, MaPhieuNhapSach = 1, MaSach = 12, SoLuongNhap = 71 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 4, MaPhieuNhapSach = 1, MaSach = 3, SoLuongNhap = 61 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 5, MaPhieuNhapSach = 1, MaSach = 30, SoLuongNhap = 131 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 6, MaPhieuNhapSach = 2, MaSach = 19, SoLuongNhap = 56 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 7, MaPhieuNhapSach = 2, MaSach = 24, SoLuongNhap = 62 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 8, MaPhieuNhapSach = 2, MaSach = 4, SoLuongNhap = 143 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 9, MaPhieuNhapSach = 2, MaSach = 7, SoLuongNhap = 123 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 10, MaPhieuNhapSach = 3, MaSach = 14, SoLuongNhap = 61 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 11, MaPhieuNhapSach = 3, MaSach = 1, SoLuongNhap = 146 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 12, MaPhieuNhapSach = 3, MaSach = 18, SoLuongNhap = 80 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 13, MaPhieuNhapSach = 3, MaSach = 9, SoLuongNhap = 81 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 14, MaPhieuNhapSach = 3, MaSach = 28, SoLuongNhap = 63 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 15, MaPhieuNhapSach = 3, MaSach = 2, SoLuongNhap = 136 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 16, MaPhieuNhapSach = 3, MaSach = 7, SoLuongNhap = 112 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 17, MaPhieuNhapSach = 4, MaSach = 19, SoLuongNhap = 117 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 18, MaPhieuNhapSach = 4, MaSach = 17, SoLuongNhap = 135 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 19, MaPhieuNhapSach = 4, MaSach = 18, SoLuongNhap = 75 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 20, MaPhieuNhapSach = 4, MaSach = 10, SoLuongNhap = 102 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 21, MaPhieuNhapSach = 4, MaSach = 5, SoLuongNhap = 74 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 22, MaPhieuNhapSach = 4, MaSach = 27, SoLuongNhap = 133 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 23, MaPhieuNhapSach = 4, MaSach = 9, SoLuongNhap = 56 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 24, MaPhieuNhapSach = 5, MaSach = 25, SoLuongNhap = 62 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 25, MaPhieuNhapSach = 5, MaSach = 27, SoLuongNhap = 125 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 26, MaPhieuNhapSach = 5, MaSach = 5, SoLuongNhap = 134 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 27, MaPhieuNhapSach = 5, MaSach = 4, SoLuongNhap = 93 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 28, MaPhieuNhapSach = 5, MaSach = 9, SoLuongNhap = 50 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 29, MaPhieuNhapSach = 5, MaSach = 28, SoLuongNhap = 113 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 30, MaPhieuNhapSach = 6, MaSach = 5, SoLuongNhap = 92 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 31, MaPhieuNhapSach = 6, MaSach = 28, SoLuongNhap = 75 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 32, MaPhieuNhapSach = 6, MaSach = 23, SoLuongNhap = 53 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 33, MaPhieuNhapSach = 6, MaSach = 16, SoLuongNhap = 62 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 34, MaPhieuNhapSach = 6, MaSach = 29, SoLuongNhap = 140 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 35, MaPhieuNhapSach = 7, MaSach = 13, SoLuongNhap = 57 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 36, MaPhieuNhapSach = 7, MaSach = 21, SoLuongNhap = 131 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 37, MaPhieuNhapSach = 7, MaSach = 4, SoLuongNhap = 147 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 38, MaPhieuNhapSach = 7, MaSach = 14, SoLuongNhap = 76 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 39, MaPhieuNhapSach = 7, MaSach = 18, SoLuongNhap = 79 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 40, MaPhieuNhapSach = 7, MaSach = 26, SoLuongNhap = 142 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 41, MaPhieuNhapSach = 8, MaSach = 23, SoLuongNhap = 51 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 42, MaPhieuNhapSach = 8, MaSach = 27, SoLuongNhap = 143 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 43, MaPhieuNhapSach = 8, MaSach = 7, SoLuongNhap = 65 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 44, MaPhieuNhapSach = 8, MaSach = 24, SoLuongNhap = 146 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 45, MaPhieuNhapSach = 8, MaSach = 25, SoLuongNhap = 122 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 46, MaPhieuNhapSach = 8, MaSach = 2, SoLuongNhap = 70 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 47, MaPhieuNhapSach = 8, MaSach = 26, SoLuongNhap = 123 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 48, MaPhieuNhapSach = 9, MaSach = 14, SoLuongNhap = 82 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 49, MaPhieuNhapSach = 9, MaSach = 16, SoLuongNhap = 76 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 50, MaPhieuNhapSach = 9, MaSach = 26, SoLuongNhap = 72 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 51, MaPhieuNhapSach = 9, MaSach = 18, SoLuongNhap = 59 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 52, MaPhieuNhapSach = 9, MaSach = 7, SoLuongNhap = 107 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 53, MaPhieuNhapSach = 9, MaSach = 20, SoLuongNhap = 59 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 54, MaPhieuNhapSach = 9, MaSach = 2, SoLuongNhap = 106 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 55, MaPhieuNhapSach = 10, MaSach = 5, SoLuongNhap = 145 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 56, MaPhieuNhapSach = 10, MaSach = 30, SoLuongNhap = 88 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 57, MaPhieuNhapSach = 10, MaSach = 27, SoLuongNhap = 71 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 58, MaPhieuNhapSach = 10, MaSach = 8, SoLuongNhap = 77 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 59, MaPhieuNhapSach = 11, MaSach = 4, SoLuongNhap = 82 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 60, MaPhieuNhapSach = 11, MaSach = 27, SoLuongNhap = 133 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 61, MaPhieuNhapSach = 11, MaSach = 10, SoLuongNhap = 125 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 62, MaPhieuNhapSach = 11, MaSach = 11, SoLuongNhap = 89 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 63, MaPhieuNhapSach = 11, MaSach = 6, SoLuongNhap = 85 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 64, MaPhieuNhapSach = 11, MaSach = 21, SoLuongNhap = 111 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 65, MaPhieuNhapSach = 12, MaSach = 18, SoLuongNhap = 51 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 66, MaPhieuNhapSach = 12, MaSach = 23, SoLuongNhap = 64 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 67, MaPhieuNhapSach = 12, MaSach = 12, SoLuongNhap = 117 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 68, MaPhieuNhapSach = 12, MaSach = 5, SoLuongNhap = 146 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 69, MaPhieuNhapSach = 12, MaSach = 8, SoLuongNhap = 96 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 70, MaPhieuNhapSach = 12, MaSach = 17, SoLuongNhap = 111 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 71, MaPhieuNhapSach = 12, MaSach = 29, SoLuongNhap = 87 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 72, MaPhieuNhapSach = 13, MaSach = 27, SoLuongNhap = 59 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 73, MaPhieuNhapSach = 13, MaSach = 17, SoLuongNhap = 115 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 74, MaPhieuNhapSach = 13, MaSach = 2, SoLuongNhap = 133 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 75, MaPhieuNhapSach = 13, MaSach = 28, SoLuongNhap = 88 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 76, MaPhieuNhapSach = 13, MaSach = 18, SoLuongNhap = 50 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 77, MaPhieuNhapSach = 14, MaSach = 9, SoLuongNhap = 87 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 78, MaPhieuNhapSach = 14, MaSach = 19, SoLuongNhap = 133 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 79, MaPhieuNhapSach = 14, MaSach = 18, SoLuongNhap = 86 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 80, MaPhieuNhapSach = 14, MaSach = 22, SoLuongNhap = 114 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 81, MaPhieuNhapSach = 14, MaSach = 20, SoLuongNhap = 62 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 82, MaPhieuNhapSach = 14, MaSach = 2, SoLuongNhap = 62 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 83, MaPhieuNhapSach = 14, MaSach = 30, SoLuongNhap = 68 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 84, MaPhieuNhapSach = 15, MaSach = 30, SoLuongNhap = 89 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 85, MaPhieuNhapSach = 15, MaSach = 29, SoLuongNhap = 69 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 86, MaPhieuNhapSach = 15, MaSach = 27, SoLuongNhap = 143 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 87, MaPhieuNhapSach = 15, MaSach = 12, SoLuongNhap = 102 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 88, MaPhieuNhapSach = 15, MaSach = 25, SoLuongNhap = 113 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 89, MaPhieuNhapSach = 16, MaSach = 14, SoLuongNhap = 86 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 90, MaPhieuNhapSach = 16, MaSach = 30, SoLuongNhap = 116 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 91, MaPhieuNhapSach = 16, MaSach = 29, SoLuongNhap = 83 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 92, MaPhieuNhapSach = 16, MaSach = 28, SoLuongNhap = 52 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 93, MaPhieuNhapSach = 16, MaSach = 4, SoLuongNhap = 141 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 94, MaPhieuNhapSach = 16, MaSach = 11, SoLuongNhap = 63 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 95, MaPhieuNhapSach = 17, MaSach = 10, SoLuongNhap = 72 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 96, MaPhieuNhapSach = 17, MaSach = 14, SoLuongNhap = 105 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 97, MaPhieuNhapSach = 17, MaSach = 16, SoLuongNhap = 65 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 98, MaPhieuNhapSach = 17, MaSach = 24, SoLuongNhap = 146 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 99, MaPhieuNhapSach = 17, MaSach = 19, SoLuongNhap = 142 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 100, MaPhieuNhapSach = 17, MaSach = 4, SoLuongNhap = 92 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 101, MaPhieuNhapSach = 17, MaSach = 12, SoLuongNhap = 76 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 102, MaPhieuNhapSach = 18, MaSach = 25, SoLuongNhap = 108 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 103, MaPhieuNhapSach = 18, MaSach = 13, SoLuongNhap = 96 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 104, MaPhieuNhapSach = 18, MaSach = 12, SoLuongNhap = 138 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 105, MaPhieuNhapSach = 18, MaSach = 23, SoLuongNhap = 54 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 106, MaPhieuNhapSach = 18, MaSach = 4, SoLuongNhap = 140 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 107, MaPhieuNhapSach = 18, MaSach = 21, SoLuongNhap = 138 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 108, MaPhieuNhapSach = 18, MaSach = 8, SoLuongNhap = 60 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 109, MaPhieuNhapSach = 19, MaSach = 2, SoLuongNhap = 80 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 110, MaPhieuNhapSach = 19, MaSach = 23, SoLuongNhap = 104 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 111, MaPhieuNhapSach = 19, MaSach = 16, SoLuongNhap = 120 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 112, MaPhieuNhapSach = 19, MaSach = 7, SoLuongNhap = 67 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 113, MaPhieuNhapSach = 19, MaSach = 21, SoLuongNhap = 148 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 114, MaPhieuNhapSach = 19, MaSach = 5, SoLuongNhap = 132 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 115, MaPhieuNhapSach = 19, MaSach = 22, SoLuongNhap = 99 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 116, MaPhieuNhapSach = 20, MaSach = 16, SoLuongNhap = 68 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 117, MaPhieuNhapSach = 20, MaSach = 22, SoLuongNhap = 143 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 118, MaPhieuNhapSach = 20, MaSach = 6, SoLuongNhap = 80 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 119, MaPhieuNhapSach = 20, MaSach = 9, SoLuongNhap = 130 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 120, MaPhieuNhapSach = 20, MaSach = 17, SoLuongNhap = 118 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 121, MaPhieuNhapSach = 20, MaSach = 13, SoLuongNhap = 53 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 122, MaPhieuNhapSach = 20, MaSach = 5, SoLuongNhap = 53 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 123, MaPhieuNhapSach = 21, MaSach = 16, SoLuongNhap = 144 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 124, MaPhieuNhapSach = 21, MaSach = 21, SoLuongNhap = 72 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 125, MaPhieuNhapSach = 21, MaSach = 30, SoLuongNhap = 130 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 126, MaPhieuNhapSach = 21, MaSach = 15, SoLuongNhap = 90 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 127, MaPhieuNhapSach = 21, MaSach = 26, SoLuongNhap = 146 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 128, MaPhieuNhapSach = 22, MaSach = 7, SoLuongNhap = 56 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 129, MaPhieuNhapSach = 22, MaSach = 1, SoLuongNhap = 79 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 130, MaPhieuNhapSach = 22, MaSach = 29, SoLuongNhap = 127 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 131, MaPhieuNhapSach = 22, MaSach = 13, SoLuongNhap = 133 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 132, MaPhieuNhapSach = 23, MaSach = 14, SoLuongNhap = 83 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 133, MaPhieuNhapSach = 23, MaSach = 10, SoLuongNhap = 84 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 134, MaPhieuNhapSach = 23, MaSach = 29, SoLuongNhap = 76 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 135, MaPhieuNhapSach = 23, MaSach = 22, SoLuongNhap = 91 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 136, MaPhieuNhapSach = 24, MaSach = 6, SoLuongNhap = 117 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 137, MaPhieuNhapSach = 24, MaSach = 1, SoLuongNhap = 111 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 138, MaPhieuNhapSach = 24, MaSach = 28, SoLuongNhap = 147 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 139, MaPhieuNhapSach = 24, MaSach = 15, SoLuongNhap = 146 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 140, MaPhieuNhapSach = 24, MaSach = 19, SoLuongNhap = 100 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 141, MaPhieuNhapSach = 24, MaSach = 23, SoLuongNhap = 100 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 142, MaPhieuNhapSach = 24, MaSach = 10, SoLuongNhap = 129 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 143, MaPhieuNhapSach = 25, MaSach = 5, SoLuongNhap = 142 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 144, MaPhieuNhapSach = 25, MaSach = 19, SoLuongNhap = 142 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 145, MaPhieuNhapSach = 25, MaSach = 2, SoLuongNhap = 122 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 146, MaPhieuNhapSach = 25, MaSach = 1, SoLuongNhap = 84 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 147, MaPhieuNhapSach = 25, MaSach = 8, SoLuongNhap = 145 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 148, MaPhieuNhapSach = 25, MaSach = 9, SoLuongNhap = 132 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 149, MaPhieuNhapSach = 25, MaSach = 10, SoLuongNhap = 55 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 150, MaPhieuNhapSach = 26, MaSach = 7, SoLuongNhap = 121 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 151, MaPhieuNhapSach = 26, MaSach = 8, SoLuongNhap = 100 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 152, MaPhieuNhapSach = 26, MaSach = 26, SoLuongNhap = 116 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 153, MaPhieuNhapSach = 26, MaSach = 1, SoLuongNhap = 84 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 154, MaPhieuNhapSach = 27, MaSach = 22, SoLuongNhap = 104 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 155, MaPhieuNhapSach = 27, MaSach = 18, SoLuongNhap = 116 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 156, MaPhieuNhapSach = 27, MaSach = 16, SoLuongNhap = 117 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 157, MaPhieuNhapSach = 27, MaSach = 24, SoLuongNhap = 149 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 158, MaPhieuNhapSach = 27, MaSach = 9, SoLuongNhap = 144 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 159, MaPhieuNhapSach = 27, MaSach = 4, SoLuongNhap = 130 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 160, MaPhieuNhapSach = 27, MaSach = 23, SoLuongNhap = 139 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 161, MaPhieuNhapSach = 28, MaSach = 26, SoLuongNhap = 65 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 162, MaPhieuNhapSach = 28, MaSach = 30, SoLuongNhap = 92 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 163, MaPhieuNhapSach = 28, MaSach = 4, SoLuongNhap = 63 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 164, MaPhieuNhapSach = 28, MaSach = 22, SoLuongNhap = 104 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 165, MaPhieuNhapSach = 28, MaSach = 9, SoLuongNhap = 122 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 166, MaPhieuNhapSach = 28, MaSach = 6, SoLuongNhap = 141 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 167, MaPhieuNhapSach = 28, MaSach = 8, SoLuongNhap = 90 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 168, MaPhieuNhapSach = 29, MaSach = 5, SoLuongNhap = 137 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 169, MaPhieuNhapSach = 29, MaSach = 8, SoLuongNhap = 66 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 170, MaPhieuNhapSach = 29, MaSach = 28, SoLuongNhap = 57 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 171, MaPhieuNhapSach = 29, MaSach = 24, SoLuongNhap = 91 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 172, MaPhieuNhapSach = 29, MaSach = 17, SoLuongNhap = 87 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 173, MaPhieuNhapSach = 29, MaSach = 6, SoLuongNhap = 142 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 174, MaPhieuNhapSach = 29, MaSach = 21, SoLuongNhap = 72 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 175, MaPhieuNhapSach = 30, MaSach = 11, SoLuongNhap = 110 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 176, MaPhieuNhapSach = 30, MaSach = 18, SoLuongNhap = 91 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 177, MaPhieuNhapSach = 30, MaSach = 23, SoLuongNhap = 127 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 178, MaPhieuNhapSach = 30, MaSach = 6, SoLuongNhap = 135 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 179, MaPhieuNhapSach = 30, MaSach = 16, SoLuongNhap = 134 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 180, MaPhieuNhapSach = 30, MaSach = 9, SoLuongNhap = 133 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 181, MaPhieuNhapSach = 30, MaSach = 26, SoLuongNhap = 127 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 182, MaPhieuNhapSach = 31, MaSach = 10, SoLuongNhap = 73 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 183, MaPhieuNhapSach = 31, MaSach = 14, SoLuongNhap = 110 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 184, MaPhieuNhapSach = 31, MaSach = 9, SoLuongNhap = 86 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 185, MaPhieuNhapSach = 31, MaSach = 6, SoLuongNhap = 51 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 186, MaPhieuNhapSach = 31, MaSach = 1, SoLuongNhap = 84 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 187, MaPhieuNhapSach = 32, MaSach = 20, SoLuongNhap = 63 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 188, MaPhieuNhapSach = 32, MaSach = 13, SoLuongNhap = 69 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 189, MaPhieuNhapSach = 32, MaSach = 2, SoLuongNhap = 60 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 190, MaPhieuNhapSach = 32, MaSach = 3, SoLuongNhap = 130 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 191, MaPhieuNhapSach = 32, MaSach = 26, SoLuongNhap = 99 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 192, MaPhieuNhapSach = 32, MaSach = 29, SoLuongNhap = 57 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 193, MaPhieuNhapSach = 33, MaSach = 3, SoLuongNhap = 69 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 194, MaPhieuNhapSach = 33, MaSach = 23, SoLuongNhap = 51 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 195, MaPhieuNhapSach = 33, MaSach = 27, SoLuongNhap = 145 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 196, MaPhieuNhapSach = 33, MaSach = 29, SoLuongNhap = 104 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 197, MaPhieuNhapSach = 33, MaSach = 24, SoLuongNhap = 92 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 198, MaPhieuNhapSach = 33, MaSach = 18, SoLuongNhap = 147 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 199, MaPhieuNhapSach = 33, MaSach = 13, SoLuongNhap = 81 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 200, MaPhieuNhapSach = 34, MaSach = 1, SoLuongNhap = 63 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 201, MaPhieuNhapSach = 34, MaSach = 3, SoLuongNhap = 121 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 202, MaPhieuNhapSach = 34, MaSach = 14, SoLuongNhap = 92 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 203, MaPhieuNhapSach = 34, MaSach = 12, SoLuongNhap = 88 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 204, MaPhieuNhapSach = 34, MaSach = 21, SoLuongNhap = 147 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 205, MaPhieuNhapSach = 34, MaSach = 30, SoLuongNhap = 60 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 206, MaPhieuNhapSach = 34, MaSach = 26, SoLuongNhap = 110 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 207, MaPhieuNhapSach = 35, MaSach = 11, SoLuongNhap = 114 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 208, MaPhieuNhapSach = 35, MaSach = 10, SoLuongNhap = 100 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 209, MaPhieuNhapSach = 35, MaSach = 13, SoLuongNhap = 85 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 210, MaPhieuNhapSach = 35, MaSach = 8, SoLuongNhap = 62 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 211, MaPhieuNhapSach = 35, MaSach = 12, SoLuongNhap = 59 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 212, MaPhieuNhapSach = 35, MaSach = 3, SoLuongNhap = 63 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 213, MaPhieuNhapSach = 36, MaSach = 3, SoLuongNhap = 117 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 214, MaPhieuNhapSach = 36, MaSach = 7, SoLuongNhap = 145 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 215, MaPhieuNhapSach = 36, MaSach = 28, SoLuongNhap = 92 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 216, MaPhieuNhapSach = 36, MaSach = 14, SoLuongNhap = 125 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 217, MaPhieuNhapSach = 36, MaSach = 5, SoLuongNhap = 102 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 218, MaPhieuNhapSach = 36, MaSach = 24, SoLuongNhap = 110 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 219, MaPhieuNhapSach = 36, MaSach = 9, SoLuongNhap = 73 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 220, MaPhieuNhapSach = 37, MaSach = 12, SoLuongNhap = 63 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 221, MaPhieuNhapSach = 37, MaSach = 24, SoLuongNhap = 136 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 222, MaPhieuNhapSach = 37, MaSach = 16, SoLuongNhap = 92 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 223, MaPhieuNhapSach = 37, MaSach = 18, SoLuongNhap = 123 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 224, MaPhieuNhapSach = 37, MaSach = 17, SoLuongNhap = 64 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 225, MaPhieuNhapSach = 38, MaSach = 5, SoLuongNhap = 92 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 226, MaPhieuNhapSach = 38, MaSach = 29, SoLuongNhap = 116 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 227, MaPhieuNhapSach = 38, MaSach = 22, SoLuongNhap = 89 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 228, MaPhieuNhapSach = 38, MaSach = 4, SoLuongNhap = 65 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 229, MaPhieuNhapSach = 38, MaSach = 2, SoLuongNhap = 75 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 230, MaPhieuNhapSach = 38, MaSach = 9, SoLuongNhap = 141 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 231, MaPhieuNhapSach = 39, MaSach = 17, SoLuongNhap = 131 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 232, MaPhieuNhapSach = 39, MaSach = 29, SoLuongNhap = 53 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 233, MaPhieuNhapSach = 39, MaSach = 9, SoLuongNhap = 68 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 234, MaPhieuNhapSach = 39, MaSach = 16, SoLuongNhap = 100 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 235, MaPhieuNhapSach = 39, MaSach = 13, SoLuongNhap = 89 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 236, MaPhieuNhapSach = 39, MaSach = 21, SoLuongNhap = 124 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 237, MaPhieuNhapSach = 40, MaSach = 23, SoLuongNhap = 95 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 238, MaPhieuNhapSach = 40, MaSach = 12, SoLuongNhap = 126 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 239, MaPhieuNhapSach = 40, MaSach = 25, SoLuongNhap = 74 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 240, MaPhieuNhapSach = 40, MaSach = 29, SoLuongNhap = 146 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 241, MaPhieuNhapSach = 40, MaSach = 11, SoLuongNhap = 74 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 242, MaPhieuNhapSach = 41, MaSach = 24, SoLuongNhap = 107 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 243, MaPhieuNhapSach = 41, MaSach = 30, SoLuongNhap = 85 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 244, MaPhieuNhapSach = 41, MaSach = 1, SoLuongNhap = 142 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 245, MaPhieuNhapSach = 41, MaSach = 15, SoLuongNhap = 112 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 246, MaPhieuNhapSach = 41, MaSach = 17, SoLuongNhap = 133 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 247, MaPhieuNhapSach = 41, MaSach = 14, SoLuongNhap = 140 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 248, MaPhieuNhapSach = 42, MaSach = 23, SoLuongNhap = 129 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 249, MaPhieuNhapSach = 42, MaSach = 19, SoLuongNhap = 131 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 250, MaPhieuNhapSach = 42, MaSach = 5, SoLuongNhap = 76 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 251, MaPhieuNhapSach = 42, MaSach = 24, SoLuongNhap = 53 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 252, MaPhieuNhapSach = 43, MaSach = 18, SoLuongNhap = 129 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 253, MaPhieuNhapSach = 43, MaSach = 19, SoLuongNhap = 92 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 254, MaPhieuNhapSach = 43, MaSach = 26, SoLuongNhap = 137 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 255, MaPhieuNhapSach = 43, MaSach = 10, SoLuongNhap = 58 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 256, MaPhieuNhapSach = 43, MaSach = 27, SoLuongNhap = 79 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 257, MaPhieuNhapSach = 43, MaSach = 3, SoLuongNhap = 86 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 258, MaPhieuNhapSach = 43, MaSach = 14, SoLuongNhap = 107 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 259, MaPhieuNhapSach = 44, MaSach = 11, SoLuongNhap = 77 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 260, MaPhieuNhapSach = 44, MaSach = 12, SoLuongNhap = 136 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 261, MaPhieuNhapSach = 44, MaSach = 6, SoLuongNhap = 98 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 262, MaPhieuNhapSach = 44, MaSach = 27, SoLuongNhap = 125 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 263, MaPhieuNhapSach = 44, MaSach = 24, SoLuongNhap = 82 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 264, MaPhieuNhapSach = 45, MaSach = 2, SoLuongNhap = 116 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 265, MaPhieuNhapSach = 45, MaSach = 6, SoLuongNhap = 95 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 266, MaPhieuNhapSach = 45, MaSach = 23, SoLuongNhap = 128 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 267, MaPhieuNhapSach = 45, MaSach = 18, SoLuongNhap = 99 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 268, MaPhieuNhapSach = 45, MaSach = 3, SoLuongNhap = 82 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 269, MaPhieuNhapSach = 46, MaSach = 12, SoLuongNhap = 95 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 270, MaPhieuNhapSach = 46, MaSach = 14, SoLuongNhap = 70 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 271, MaPhieuNhapSach = 46, MaSach = 5, SoLuongNhap = 95 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 272, MaPhieuNhapSach = 46, MaSach = 4, SoLuongNhap = 145 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 273, MaPhieuNhapSach = 47, MaSach = 23, SoLuongNhap = 72 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 274, MaPhieuNhapSach = 47, MaSach = 17, SoLuongNhap = 55 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 275, MaPhieuNhapSach = 47, MaSach = 8, SoLuongNhap = 105 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 276, MaPhieuNhapSach = 47, MaSach = 20, SoLuongNhap = 82 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 277, MaPhieuNhapSach = 47, MaSach = 6, SoLuongNhap = 103 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 278, MaPhieuNhapSach = 47, MaSach = 22, SoLuongNhap = 102 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 279, MaPhieuNhapSach = 47, MaSach = 11, SoLuongNhap = 108 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 280, MaPhieuNhapSach = 48, MaSach = 14, SoLuongNhap = 88 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 281, MaPhieuNhapSach = 48, MaSach = 18, SoLuongNhap = 95 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 282, MaPhieuNhapSach = 48, MaSach = 25, SoLuongNhap = 98 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 283, MaPhieuNhapSach = 48, MaSach = 3, SoLuongNhap = 51 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 284, MaPhieuNhapSach = 48, MaSach = 8, SoLuongNhap = 107 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 285, MaPhieuNhapSach = 48, MaSach = 6, SoLuongNhap = 135 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 286, MaPhieuNhapSach = 48, MaSach = 20, SoLuongNhap = 67 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 287, MaPhieuNhapSach = 49, MaSach = 30, SoLuongNhap = 128 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 288, MaPhieuNhapSach = 49, MaSach = 4, SoLuongNhap = 91 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 289, MaPhieuNhapSach = 49, MaSach = 29, SoLuongNhap = 112 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 290, MaPhieuNhapSach = 49, MaSach = 16, SoLuongNhap = 133 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 291, MaPhieuNhapSach = 49, MaSach = 13, SoLuongNhap = 69 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 292, MaPhieuNhapSach = 49, MaSach = 24, SoLuongNhap = 129 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 293, MaPhieuNhapSach = 50, MaSach = 14, SoLuongNhap = 103 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 294, MaPhieuNhapSach = 50, MaSach = 11, SoLuongNhap = 88 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 295, MaPhieuNhapSach = 50, MaSach = 19, SoLuongNhap = 135 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 296, MaPhieuNhapSach = 50, MaSach = 5, SoLuongNhap = 127 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 297, MaPhieuNhapSach = 50, MaSach = 22, SoLuongNhap = 125 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 298, MaPhieuNhapSach = 50, MaSach = 13, SoLuongNhap = 111 },
                new ChiTietPhieuNhap { MaChiTietPhieuNhap = 299, MaPhieuNhapSach = 50, MaSach = 8, SoLuongNhap = 57 }
            );
        }

        private static void SeedSach(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Sach>().HasData(
                new Sach { MaSach = 1, TenSach = "Lập Trình C# Cơ Bản", TheLoai = "Công Nghệ Thông Tin", TacGia = "Nguyễn Văn A", SoLuongTon = 128 },
                new Sach { MaSach = 2, TenSach = "Clean Code", TheLoai = "Lập Trình", TacGia = "Robert C. Martin", SoLuongTon = 274 },
                new Sach { MaSach = 3, TenSach = "Design Patterns: Elements of Reusable Object-Oriented Software", TheLoai = "Lập Trình", TacGia = "Erich Gamma", SoLuongTon = 197 },
                new Sach { MaSach = 4, TenSach = "Introduction to Algorithms", TheLoai = "Toán Tin", TacGia = "Thomas H. Cormen", SoLuongTon = 53 },
                new Sach { MaSach = 5, TenSach = "The Pragmatic Programmer", TheLoai = "Lập Trình", TacGia = "Andrew Hunt", SoLuongTon = 291 },
                new Sach { MaSach = 6, TenSach = "Artificial Intelligence: A Modern Approach", TheLoai = "Trí Tuệ Nhân Tạo", TacGia = "Stuart Russell", SoLuongTon = 88 },
                new Sach { MaSach = 7, TenSach = "Deep Learning", TheLoai = "Trí Tuệ Nhân Tạo", TacGia = "Ian Goodfellow", SoLuongTon = 120 },
                new Sach { MaSach = 8, TenSach = "Refactoring: Improving the Design of Existing Code", TheLoai = "Lập Trình", TacGia = "Martin Fowler", SoLuongTon = 265 },
                new Sach { MaSach = 9, TenSach = "Effective Java", TheLoai = "Lập Trình", TacGia = "Joshua Bloch", SoLuongTon = 144 },
                new Sach { MaSach = 10, TenSach = "Python Crash Course", TheLoai = "Lập Trình", TacGia = "Eric Matthes", SoLuongTon = 203 },
                new Sach { MaSach = 11, TenSach = "You Don't Know JS", TheLoai = "Lập Trình", TacGia = "Kyle Simpson", SoLuongTon = 75 },
                new Sach { MaSach = 12, TenSach = "The C Programming Language", TheLoai = "Lập Trình", TacGia = "Brian W. Kernighan", SoLuongTon = 55 },
                new Sach { MaSach = 13, TenSach = "Cracking the Coding Interview", TheLoai = "Lập Trình", TacGia = "Gayle Laakmann McDowell", SoLuongTon = 280 },
                new Sach { MaSach = 14, TenSach = "Code Complete", TheLoai = "Lập Trình", TacGia = "Steve McConnell", SoLuongTon = 210 },
                new Sach { MaSach = 15, TenSach = "Head First Design Patterns", TheLoai = "Lập Trình", TacGia = "Eric Freeman", SoLuongTon = 95 },
                new Sach { MaSach = 16, TenSach = "Working Effectively with Legacy Code", TheLoai = "Lập Trình", TacGia = "Michael Feathers", SoLuongTon = 156 },
                new Sach { MaSach = 17, TenSach = "Domain-Driven Design", TheLoai = "Phát Triển Phần Mềm", TacGia = "Eric Evans", SoLuongTon = 247 },
                new Sach { MaSach = 18, TenSach = "The Mythical Man-Month", TheLoai = "Phát Triển Phần Mềm", TacGia = "Frederick P. Brooks Jr.", SoLuongTon = 132 },
                new Sach { MaSach = 19, TenSach = "Structure and Interpretation of Computer Programs", TheLoai = "Khoa Học Máy Tính", TacGia = "Harold Abelson", SoLuongTon = 198 },
                new Sach { MaSach = 20, TenSach = "Clean Architecture", TheLoai = "Phát Triển Phần Mềm", TacGia = "Robert C. Martin", SoLuongTon = 121 },
                new Sach { MaSach = 21, TenSach = "JavaScript: The Good Parts", TheLoai = "Lập Trình", TacGia = "Douglas Crockford", SoLuongTon = 205 },
                new Sach { MaSach = 22, TenSach = "Learning Python", TheLoai = "Lập Trình", TacGia = "Mark Lutz", SoLuongTon = 140 },
                new Sach { MaSach = 23, TenSach = "Programming Pearls", TheLoai = "Lập Trình", TacGia = "Jon Bentley", SoLuongTon = 80 },
                new Sach { MaSach = 24, TenSach = "Effective C++", TheLoai = "Lập Trình", TacGia = "Scott Meyers", SoLuongTon = 91 },
                new Sach { MaSach = 25, TenSach = "Introduction to the Theory of Computation", TheLoai = "Khoa Học Máy Tính", TacGia = "Michael Sipser", SoLuongTon = 72 },
                new Sach { MaSach = 26, TenSach = "Algorithms", TheLoai = "Khoa Học Máy Tính", TacGia = "Robert Sedgewick", SoLuongTon = 177 },
                new Sach { MaSach = 27, TenSach = "The Clean Coder", TheLoai = "Lập Trình", TacGia = "Robert C. Martin", SoLuongTon = 98 },
                new Sach { MaSach = 28, TenSach = "Introduction to Machine Learning with Python", TheLoai = "Trí Tuệ Nhân Tạo", TacGia = "Andreas C. Müller", SoLuongTon = 63 },
                new Sach { MaSach = 29, TenSach = "Hands-On Machine Learning with Scikit-Learn, Keras, and TensorFlow", TheLoai = "Trí Tuệ Nhân Tạo", TacGia = "Aurélien Géron", SoLuongTon = 84 },
                new Sach { MaSach = 30, TenSach = "Test Driven Development: By Example", TheLoai = "Lập Trình", TacGia = "Kent Beck", SoLuongTon = 102 }
            );
        }
    }
}